# Generated by Django 4.2.27 on 2026-01-03 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='squareoffrule',
            options={},
        ),
        migrations.AddField(
            model_name='squareoffrule',
            name='dry_run',
            field=models.BooleanField(default=True, help_text='If true, log actions but do not place orders'),
        ),
        migrations.AddField(
            model_name='squareoffrule',
            name='instrument_token',
            field=models.CharField(blank=True, help_text='Instrument token for the symbol (from broker)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='squareoffrule',
            name='kill_switch',
            field=models.BooleanField(default=False, help_text='If true, disable all trading instantly'),
        ),
        migrations.AlterField(
            model_name='squareoffrule',
            name='active',
            field=models.BooleanField(default=True, help_text='Is this rule currently active?'),
        ),
        migrations.AlterField(
            model_name='squareoffrule',
            name='symbol',
            field=models.CharField(blank=True, help_text='Trading symbol (e.g., NIFTY 50)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='squareoffrule',
            name='trigger_price',
            field=models.DecimalField(decimal_places=2, help_text='Price at which to trigger square-off', max_digits=10),
        ),
        migrations.AlterField(
            model_name='squareoffrule',
            name='triggered_today',
            field=models.BooleanField(default=False, help_text='Has this rule been triggered today?'),
        ),
        migrations.CreateModel(
            name='TradeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(help_text='e.g., TICK, TRIGGER, ORDER_PLACED, ORDER_FAILED', max_length=50)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.squareoffrule')),
            ],
        ),
    ]
