# Generated by Django 4.2.27 on 2026-01-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_alter_squareoffrule_options_squareoffrule_dry_run_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squareoffrule',
            name='trigger_price',
        ),
        migrations.AddField(
            model_name='squareoffrule',
            name='lower_limit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price at which to trigger square-off if price falls below this level', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='squareoffrule',
            name='upper_limit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price at which to trigger square-off if price rises above this level', max_digits=10, null=True),
        ),
    ]
